name: Run API Documentation Generator Script
on:
  push:
    branches:
      - release_csv
    # paths:
    #   - swagger/**

jobs:  
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Developer Portal Definitions Repo
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node_version: 18

      - name: Run Script
        run: node index.js
      
      - name: Print out csv file
        run: cat apis.csv
      
      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      
      - name: Generate Release Tag
        id: date
        run: echo "::set-output name=timestamp::$(date +'%Y-%m-%d_%H-%M-%S')"
      
      - name: Release new CSV
        id: release_csv
        uses: softprops/action-gh-release@v1
        with:
          files: |
            apis.csv
          tag_name: ${{ steps.date.outputs.timestamp }}
          
